AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Managed Grafana workspace with CloudWatch and SNS integration'

Parameters:
  WorkspaceName:
    Type: String
    Default: 'GrafanaWorkspaceProject'
    Description: 'Name of the Grafana workspace'

Resources:
  GrafanaWorkspaceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: grafana.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess
      Policies:
        - PolicyName: GrafanaSNSPublish
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sns:Publish
                Resource: arn:aws:sns:us-east-1:677276086106:grafana-alert-topic

  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      Name: !Ref WorkspaceName
      AccountAccessType: CURRENT_ACCOUNT
      AuthenticationProviders:
        - AWS_SSO
      PermissionType: SERVICE_MANAGED
      RoleArn: !GetAtt GrafanaWorkspaceRole.Arn
